{% set name = "iscd-linearelasticity" %}
{% set version = "0.0.0rc0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # there are no tagged releases which so using archives of specific commits
  url: https://github.com/ISCDtoolbox/LinearElasticity/archive/58ace131fd1af9293ded9f84f2a6447147a8ecdc.zip
  sha256: 6fc97e876ed1699e914cae97da96571c2269e3b43abfef2dda7b9999551e21f2

build:
  number: 0
  skip: true  # [py<3 or win] # Cannot open include file: 'pthread.h': No such file or directory
  ignore_run_exports_from:
    - {{ compiler('cxx') }}
  run_exports:
    - iscd-linearelasticity {{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]
    - iscd-commons
  run:
    - iscd-commons

test:
  commands:
    - elastic || true  # [unix]
    - test -f $PREFIX/lib/libElas.so  # [linux]
    - test -f $PREFIX/lib/libElas.dylib  # [osx]
    - test -f $PREFIX/include/elastic.h
    - test -f $PREFIX/include/ls_calls.h

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'ISCD - Elastic'
  description: |
    Elastic is a simple yet efficient finite element solver for linear elasticity problems in two and three dimensions.
  doc_url: https://github.com/ISCDtoolbox/LinearElasticity/wiki
  dev_url: https://github.com/ISCDtoolbox/LinearElasticity

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
