{% set name = "iscd-linearelasticity" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ISCDtoolbox/LinearElasticity/archive/refs/tags/v{{ version }}.zip
  sha256: 8abd64945ff05bd6501399c91ff712bc61386801acce5b5bd1611f273d256ac7
  patches:
    - CMakeLists.patch

build:
  number: 0
  skip: true  # [py<3 or win] # Cannot open include file: 'pthread.h': No such file or directory
  run_exports:
    - {{ pin_subpackage('iscd-linearelasticity', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]
    - iscd-commons
  run:
    - iscd-commons

test:
  commands:
    - elastic || true  # [unix]
    - test -f $PREFIX/lib/libElas.so  # [linux]
    - test -f $PREFIX/lib/libElas.dylib  # [osx]
    - test -f $PREFIX/include/elastic.h
    - test -f $PREFIX/include/ls_calls.h

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'ISCD - Elastic'
  description: |
    Elastic is a simple yet efficient finite element solver for linear elasticity problems in two and three dimensions.
  doc_url: https://github.com/ISCDtoolbox/LinearElasticity/wiki
  dev_url: https://github.com/ISCDtoolbox/LinearElasticity

extra:
  recipe-maintainers:
    - ldallolio
    - fbordeu
